name: Automatic Deployment

# When this runs
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Get the code
      - name: Download code
        uses: actions/checkout@v4

      # Prepare Docker
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      # Connect to GitHub to store the image
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Create and upload the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest